apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jrhn0si52-go
  janus-idp.io/tekton: jrhn0si52-go
  backstage.io/kubernetes-id: jrhn0si52-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jrhn0si52-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
