apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jrhn0si52-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jrhn0si52-go 
  name: jrhn0si52-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jrhn0si52-go 
